config/routes.rb
Rails.application.routes.draw do
  resources :sounds

  root 'sounds#index'

end

app/models/sound.rb
class Sound < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]

  respond_to :xml, only: [:index]

  def index
    @sounds = Sound.all
  end

  def new
    @sound = Sound.new
  end

  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render :show, status: :created, location: @sound }
      else
        format.html { render :new }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sound.destroy
    respond_to do |format|
      format.html { redirect_to sounds_url, notice: 'Sound was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.require(:sound).permit(:name, :image_url, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundboardify</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://apis.google.com/js/platform.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.xml.erb
<?xml version="1.0" encoding="UTF-8" ?>
<Module>
<!-- Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License
-->
  <ModulePrefs title="Soundboardify"
               description="A collection of fun sound clips"
               author="Spencer Davis, Json Vanderslice">
          <Require feature="rpc" />
          <Require feature="views" />\
          <Require feature="locked-domain" /> \
  </ModulePrefs>
  <Content type="html">
    <![CDATA[

    <html>
      <head>
        <title>Soundboardify</title>
        <%= stylesheet_link_tag 'application' %>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
      </head>
      <body>
        <%= yield %>
        <%= javascript_include_tag "https://apis.google.com/js/platform.js" %>
        <%= javascript_include_tag "https://plus.google.com/hangouts/_/api/v1/hangout.js" %>
        <%= javascript_include_tag 'application' %>
      </body>
    </html>

    ]]>
  </Content>
</Module>

app/views/sounds/_form.html.erb
<%= form_for(@sound) do |f| %>
  <% if @sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% @sound.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sounds/edit.html.erb
<h1>Editing sound</h1>

<%= render 'form' %>

<%= link_to 'Show', @sound %> |
<%= link_to 'Back', sounds_path %>

app/views/sounds/index.html.erb
Install Soundboardify Hangout App<br>

<div class="g-hangout" data-render="createhangout"
    data-initial_apps="[{ app_id : '271682765448', start_data : 'dQw4w9WgXcQ', 'app_type' : 'ROOM_APP' }]">
</div>

app/views/sounds/index.xml.erb
<div id='soundboardify' style='visibility:hidden;'>
  <h4>soundboardify</h4>
  <% @sounds.each do |sound| %>
    <div class="sound-wrap" data-url="<%= sound.url %>">
      <img src="<%= sound.image_url %>" class="sound" title="<%= sound.name %>" />
      <span class="sound-title">
        <%= sound.name %>
      </span>
    </div>
  <% end %>
</div>

app/views/sounds/new.html.erb
<h1>New sound</h1>

<%= render 'form' %>

<%= link_to 'Back', sounds_path %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sound.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @sound.image_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @sound.url %>
</p>

<%= link_to 'Edit', edit_sound_path(@sound) %> |
<%= link_to 'Back', sounds_path %>